site:
    title: "行云小站"
    subtitle: "Say hello to you!"
    limit: 10
    theme: theme-cream
    lang: zh
    url: "https://w568w.eu.org/"
    comment: username
    logo: "-/images/avatar.gif"
    # link: "{category}/{year}/{month}/{day}/{title}.html"
    # root: "/blog"
    config:
        GitHub: "https://github.com/w568w"
        CustomPage:
            Link: gays
            Title: 朋友们

authors:
    w568w:
        name: "w568w"
        intro: "梦想改变自己的疯子。"
        avatar: "-/images/avatar.gif"

build:
    output: "public"
    port: 8000
    # Copied files to public folder when build
    copy:
        - "source/images"
    # Excuted command when use 'ink publish'
    publish: |
        git add . -A
        git commit -m "a"
        git push origin
